apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mvdcreativo/apisix-argocd.git
    path: manifests
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true