apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: dev0
spec:
  project: default
  source:
    repoURL: https://github.com/mvdcreativo/apisix-argocd.git
    path: manifests
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true