apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: pokemon-route
  namespace: dev0
spec:
  http:
  - name: pokemon-rule
    match:
      hosts:
      - pokemon.example.com
      paths:
      - /
    backends:
    - serviceName: pokemon-upstream
      servicePort: 443
      weight: 100
