apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: test-app-route
  namespace: dev0
spec:
  http:
  - name: test-app-rule
    match:
      hosts:
      - test-app.example.com
      paths:
      - /test
    backends:
    - serviceName: test-app
      servicePort: 80
